spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vehicle_trading_db
    username: postgres
    password: 27021
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 593647877348-6l05ob2su91rdfdku71s9h1at5fl4hol.apps.googleusercontent.com
            client-secret: GOCSPX-iKAUTCfvh71PHeMblQ_bKDQmw
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          github:
            client-id: Ov23liPjBomC7v1tpBW9
            client-secret: 187c9951de08cda866df143705a71a5ceb62129c
            scope:
              - read:user
              - user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration: 900000  # 15 minutes in milliseconds

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
  default-produces-media-type: application/json

server:
  port: 8081
